package com.java.store.enums;

public enum Permission {
    PRODUCT_READ, PRODUCT_WRITE, PRODUCT_ADD, PRODUCT_DELETE,
    USER_READ, USER_WRITE, USER_ADD, USER_DELETE,
    CART_READ, CART_WRITE, CART_ADD, CART_DELETE,
    DISCOUNT_READ, DISCOUNT_WRITE, DISCOUNT_ADD, DISCOUNT_DELETE,
    REVIEW_READ, REVIEW_WRITE, REVIEW_ADD, REVIEW_DELETE;
}
